# Generated by Django 4.0

from django.db import migrations

STATUSES = [
    {'id': 1, 'code': 'CREATED', 'name': 'Order Created'},
    {'id': 2, 'code': 'RATE_APPROVAL', 'name': 'Rate Approval'},
    {'id': 3, 'code': 'BILLING', 'name': 'Billing'},
    {'id': 4, 'code': 'NEED_APPROVAL', 'name': 'Need Approval'},
    {'id': 5, 'code': 'BILLING_PENDING', 'name': 'Billing Pending'},
    {'id': 6, 'code': 'APPROVED', 'name': 'Approved'},
    {'id': 7, 'code': 'REJECTED', 'name': 'Rejected'},
    {'id': 8, 'code': 'BILLING_REJECTED', 'name': 'Billing Rejected'},
    {'id': 9, 'code': 'COMPLETED', 'name': 'Completed'},
    {'id': 10, 'code': 'AUDITOR_APPROVAL', 'name': 'Auditor Approval'},
]

def populate_statuses(apps, schema_editor):
    try:
        OrderStatus = apps.get_model('orders', 'OrderStatus')
    except LookupError:
        return

    for status_data in STATUSES:
        OrderStatus.objects.update_or_create(
            id=status_data['id'],
            defaults={
                'code': status_data['code'],
                'name': status_data['name']
            }
        )

def remove_statuses(apps, schema_editor):
    try:
        OrderStatus = apps.get_model('orders', 'OrderStatus')
    except LookupError:
        return

    status_ids = [s['id'] for s in STATUSES]
    OrderStatus.objects.filter(id__in=status_ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_statuses, reverse_code=remove_statuses),
    ]