# Generated by Django 6.0.1 on 2026-02-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_userrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
