# Generated by Django 6.0.1 on 2026-02-10 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_basic_price_orderslog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'order_statuses',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='orderslog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderslog',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderstatus'),
        ),
    ]
