# Generated by Django 6.0.1 on 2026-02-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatus_alter_orderslog_performed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderslog',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
    ]
