# Generated by Django 6.0.1 on 2026-02-12 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderslog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpl_id', models.CharField(blank=True, max_length=100, null=True)),
                ('bpl_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(db_column='status', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus'),
        ),
    ]
