# Generated by Django 6.0.1 on 2026-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_branches_alter_order_bill_to_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
