# Generated by Django 6.0.1 on 2026-02-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sap_created',
            field=models.BooleanField(default=False),
        ),
    ]
