# Generated by Django 6.0.1 on 2026-02-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_sap_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remakrs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
