# Generated by Django 6.0.1 on 2026-02-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_remakrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='remakrs',
            new_name='remarks',
        ),
    ]
