# Generated by Django 6.0.1 on 2026-03-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_populate_order_statuses'),
        ('orders', '0011_rename_remakrs_order_remarks'),
    ]

    operations = [
    ]
