# Generated by Django 6.0.1 on 2026-03-04 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_merge_20260304_1123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPartyAssignment',
        ),
        migrations.AlterModelOptions(
            name='branches',
            options={'managed': False, 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='dispatchlocation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='orderslog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Order Status', 'verbose_name_plural': 'Order Statuses'},
        ),
        migrations.AlterModelOptions(
            name='parties',
            options={'verbose_name_plural': 'Parties'},
        ),
        migrations.AlterModelOptions(
            name='partyaddress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={},
        ),
        
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_to_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatch_from_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='dispatch_from_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_to_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ltrs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
