# Generated by Django 6.0.1 on 2026-03-04 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_delete_userpartyassignment_alter_branches_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parties',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='parties',
            name='country',
        ),
        migrations.RemoveField(
            model_name='partyaddress',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='partyaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partyaddress',
            name='party_id',
        ),
        migrations.RemoveField(
            model_name='partyaddress',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='productdetails',
            name='synced_at',
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispatchlocation',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parties',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='address_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchlocation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderslog',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus'),
        ),
        migrations.AlterField(
            model_name='orderslog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderslog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderslog',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parties',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='card_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='card_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parties',
            name='main_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parties',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partyaddress',
            name='address_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partyaddress',
            name='full_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partyaddress',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='item_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='sal_factor2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterModelTable(
            name='orderslog',
            table='orders_log',
        ),
        migrations.AlterModelTable(
            name='parties',
            table='parties',
        ),
        migrations.AlterModelTable(
            name='partyaddress',
            table='party_addresses',
        ),
        migrations.AlterModelTable(
            name='productdetails',
            table='product_details',
        ),
    ]
