# Generated by Django 6.0.1 on 2026-03-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchlocation',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.orderstatus'),
        ),
    ]
