# Generated by Django 6.0.3 on 2026-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_scheme_orderitem_qty_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_scheme_visible',
            field=models.BooleanField(default=False),
        ),
    ]
