# Generated by Django 6.0.1 on 2026-01-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('card_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('main_group', models.CharField(blank=True, max_length=100, null=True)),
                ('chain', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('card_type', models.CharField(choices=[('C', 'Customer'), ('S', 'Supplier'), ('L', 'Lead')], default='C', max_length=1)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'db_table': 'sap_parties',
                'ordering': ['card_code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], max_length=20, null=True)),
                ('sal_factor2', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_deleted', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('sal_pack_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sap_products',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('PRODUCT', 'Products'), ('PARTY', 'Parties'), ('PARTY_ADDRESS', 'Party Addresses'), ('ALL', 'All')], max_length=20)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='STARTED', max_length=10)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
            ],
            options={
                'db_table': 'sap_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sync_type', models.CharField(choices=[('PRODUCT', 'Products'), ('PARTY', 'Parties'), ('PARTY_ADDRESS', 'Party Addresses'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('frequency', models.CharField(choices=[('HOURLY', 'Every Hour'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom Interval')], default='DAILY', max_length=20)),
                ('custom_interval_minutes', models.IntegerField(default=60, help_text='Used when frequency is CUSTOM')),
                ('hour', models.IntegerField(default=6, help_text='Hour of day for DAILY sync (0-23)')),
                ('is_active', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sap_sync_schedules',
            },
        ),
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(db_index=True, max_length=50)),
                ('address_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.CharField(blank=True, choices=[('B', 'Bill To'), ('S', 'Ship To')], max_length=1, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='sap_sync.party')),
            ],
            options={
                'verbose_name_plural': 'Party Addresses',
                'db_table': 'sap_party_addresses',
                'ordering': ['card_code', 'address_id'],
                'unique_together': {('card_code', 'address_id')},
            },
        ),
    ]
