# Generated by Django 4.2.16 on 2026-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0002_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
