# Generated by Django 4.2.16 on 2026-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0003_product_tax_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['card_code']},
        ),
        migrations.AlterModelOptions(
            name='partyaddress',
            options={'ordering': ['card_code', 'address_name']},
        ),
        migrations.RenameField(
            model_name='partyaddress',
            old_name='address_id',
            new_name='city',
        ),
        migrations.AlterUniqueTogether(
            name='partyaddress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='party',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='address_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='card_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='party',
            name='card_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='card_type',
            field=models.CharField(default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partyaddress',
            name='address_type',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partyaddress',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('card_code', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='partyaddress',
            unique_together={('card_code', 'address_name', 'category')},
        ),
        migrations.RemoveField(
            model_name='party',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partyaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partyaddress',
            name='party',
        ),
    ]
