# Generated by Django 4.2.16 on 2026-02-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0004_alter_party_options_alter_partyaddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax_code',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_code',
            field=models.CharField(max_length=50),
        ),
    ]
