# Generated by Django 4.2.16 on 2026-02-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0005_remove_product_tax_code_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('item_code', 'category')},
        ),
    ]
