# Generated by Django 4.2.16 on 2026-02-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0006_alter_product_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='gst_number',
        ),
    ]
