# Generated by Django 6.0.1 on 2026-02-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0008_salesquotationlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False, 'ordering': ['category', 'bpl_id'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
