# Generated by Django 6.0.1 on 2026-03-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0009_alter_branch_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='s',
        ),
    ]
