# Generated by Django 6.0.3 on 2026-04-10 07:12

from django.db import migrations


def rename_product_table_if_needed(apps, schema_editor):
    Product = apps.get_model('sap_sync', 'Product')
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if 's' in existing_tables and 'sap_products' not in existing_tables:
        schema_editor.alter_db_table(Product, 's', 'sap_products')


def revert_product_table_name_if_needed(apps, schema_editor):
    Product = apps.get_model('sap_sync', 'Product')
    existing_tables = set(schema_editor.connection.introspection.table_names())

    if 'sap_products' in existing_tables and 's' not in existing_tables:
        schema_editor.alter_db_table(Product, 'sap_products', 's')


class Migration(migrations.Migration):

    dependencies = [
        ('sap_sync', '0010_alter_product_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    rename_product_table_if_needed,
                    reverse_code=revert_product_table_name_if_needed,
                ),
            ],
            state_operations=[
                migrations.AlterModelTable(
                    name='product',
                    table='sap_products',
                ),
            ],
        ),
    ]
