# Generated by Django 6.0.1 on 2026-01-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='main_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_group',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.maingroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.state'),
        ),
    ]
