# Generated by Django 6.0.1 on 2026-02-19 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userrole_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyProductAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(db_index=True, max_length=50)),
                ('item_code', models.CharField(db_index=True, max_length=50)),
                ('category', models.CharField(choices=[('OIL', 'Oil'), ('BEVERAGES', 'Beverages'), ('MART', 'Mart')], db_index=True, max_length=20)),
                ('basic_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_product_assignments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'party_product_assignments',
                'ordering': ['card_code', 'item_code', 'category'],
                'unique_together': {('card_code', 'item_code', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserPartyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.CharField(db_index=True, max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_party_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'card_code')},
            },
        ),
    ]
