# Generated by Django 6.0.3 on 2026-04-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_schemeproduct_product_schemeproduct_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='users.state')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='users.user')),
            ],
            options={
                'db_table': 'users_user_states',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='schemeproduct',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
