# Generated by Django 6.0.3 on 2026-04-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userstate_alter_schemeproduct_item_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemeproduct',
            name='state',
        ),
        migrations.AddField(
            model_name='schemeproduct',
            name='state_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='main_groups',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='m2m_users',
                        to='users.maingroup',
                    ),
                ),
                migrations.AddField(
                    model_name='user',
                    name='states',
                    field=models.ManyToManyField(
                        blank=True,
                        related_name='m2m_users',
                        to='users.state',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]